import { Router } from "express";
import fetchAllOrders from "../controllers/product.controllers/fetchAllOrders.js";
import getOrder from "../controllers/product.controllers/getOrder.js";
import createOrder from "../controllers/product.controllers/createOrder.js";
import paypalCreateOrder from "../controllers/product.controllers/paypalCreateOrder.js";
import paypalCaptureOrder from "../controllers/product.controllers/paypalCaptureOrder.js";
const orderRouter = Router();
orderRouter.get("/", fetchAllOrders);
orderRouter.get("/:id", getOrder);
orderRouter.post("/", createOrder);
orderRouter.post("/create-paypal-order", paypalCreateOrder);
orderRouter.post("/capture-paypal-order", paypalCaptureOrder);
export default orderRouter;
