import { Router } from "express";
import addProduct from "../controllers/product.controllers/addProduct.js";
import updateProduct from "../controllers/product.controllers/updateProduct.js";
import fetchProducts from "../controllers/product.controllers/fetchProducts.js";
import deleteProduct from "../controllers/product.controllers/deleteProduct.js";
import getProduct from "../controllers/product.controllers/getProduct.js";
import createOrder from "../controllers/product.controllers/createOrder.js";
import fetchAllOrders from "../controllers/product.controllers/fetchAllOrders.js";
import getOrder from "../controllers/product.controllers/getOrder.js";
const productRouter = Router();
productRouter.get("/", fetchProducts);
productRouter.get("/:id", getProduct);
productRouter.get("/:id", getOrder);
productRouter.post("/add", addProduct);
productRouter.post("/order", createOrder);
productRouter.put("/update/:id", updateProduct);
productRouter.delete("/:id", deleteProduct);
productRouter.get("/orders", fetchAllOrders);
export default productRouter;
